//! # Complex sequences.
//! resources/imgui-learning/01_basic_interactivity.rs
//!
//! **(AI) - Code generated by Gemini CLI.**
//! This file demonstrates basic ImGui interactivity, state management via closures,
//! and common widgets for a fractal settings panel.
//! Explicit namespacing is used for clarity (e.g., imgui::Ui).

use imgui;

mod support;

fn main() {
    // -------------------------------------------------------------------------
    // 1. APPLICATION STATE
    // -------------------------------------------------------------------------
    let mut fractal_type = 0;
    let mut iterations: i32 = 100;
    let mut zoom: f32 = 1.0;
    let mut offset_x: f32 = 0.0;
    let mut offset_y: f32 = 0.0;
    let mut color_base: [f32; 3] = [0.2, 0.5, 0.8]; // RGB
    let mut show_grid = true;

    // -------------------------------------------------------------------------
    // 2. UI SETUP
    // -------------------------------------------------------------------------
    support::init_with_startup(
        "Complex Sequences - Settings Lab",
        |_, _, _| {
            println!("System initialized.");
        },
        move |_, ui: &mut imgui::Ui| {
            // -----------------------------------------------------------------
            // 3. WINDOW DEFINITION
            // -----------------------------------------------------------------
            ui.window("Fractal Settings")
                .size([300.0, 500.0], imgui::Condition::FirstUseEver)
                .position([10.0, 10.0], imgui::Condition::FirstUseEver)
                .build(|| {
                    
                    ui.text_wrapped("Adjust the parameters below to control the simulation.");
                    ui.separator();

                    // ---------------------------------------------------------
                    // 4. WIDGETS & LOGIC
                    // ---------------------------------------------------------
                    
                    ui.text("Fractal Type:");
                    ui.radio_button("Mandelbrot", &mut fractal_type, 0);
                    ui.same_line(); 
                    ui.radio_button("Julia", &mut fractal_type, 1);
                    ui.same_line();
                    ui.radio_button("Newton", &mut fractal_type, 2);
                    
                    ui.separator();

                    ui.text("Simulation:");
                    
                    // In imgui-rs 0.12, simple widgets are direct methods on Ui
                    ui.slider("Iterations", 1, 1000, &mut iterations);

                    // Advanced configuration uses _config methods
                    ui.slider_config("Zoom", 0.1, 100.0)
                        .flags(imgui::SliderFlags::LOGARITHMIC)
                        .build(&mut zoom);

                    ui.separator();

                    ui.text("Visuals:");
                    
                    // Color settings also have a config method
                    ui.color_edit3_config("Base Color", &mut color_base)
                        .flags(imgui::ColorEditFlags::PICKER_HUE_WHEEL)
                        .build();

                    ui.checkbox("Show Grid Overlay", &mut show_grid);

                    ui.separator();

                    if ui.button("Reset Settings") {
                        zoom = 1.0;
                        offset_x = 0.0;
                        offset_y = 0.0;
                        iterations = 100;
                        println!("Settings reset!");
                    }
                });

            // -----------------------------------------------------------------
            // 5. DEBUG / DEMO DISPLAY
            // -----------------------------------------------------------------
            ui.window("Debug Info")
                .size([200.0, 150.0], imgui::Condition::FirstUseEver)
                .position([320.0, 10.0], imgui::Condition::FirstUseEver)
                .build(|| {
                    ui.text(format!("Current Zoom: {:.4}", zoom));
                    ui.text(format!("Position: ({:.2}, {:.2})", offset_x, offset_y));
                    ui.text(format!("Color: {:?}", color_base));
                    
                    if show_grid {
                         ui.text_colored([0.0, 1.0, 0.0, 1.0], "Grid is ACTIVE");
                    } else {
                         ui.text_colored([1.0, 0.0, 0.0, 1.0], "Grid is HIDDEN");
                    }
                });
        },
    );
}